AddLocationForm:

<AddLocationForm>:
    orientation: 'vertical'
    BoxLayout:
        height: "40dp"
        size_hint_y:None  
        TextInput:
            size_hint_x:50
        Button:
            text: 'Buscar'
            size_hint_x:25
            on_press: root.search_location()
        Button:
            text: 'Posicion Actual'
            size_hint_x:25
    ListView:
        item_strings:["Palo Alto, MX", "Palo Alto, US"]